### ISSUE TITLE
Version appears to be out of date

### ISSUE THREAD

**Issue by evanpurkhiser** [bflad/chef-wkhtmltopdf#3]
Looks like they don't keep around old versions on the sourceforge page. Also looks like they ditech SHA build IDs.

**Comment by klamontagne** [comment]
The file name changed with version 0.12.1, as well as the archive type (xz -> bz2).

0.12.0 is now in a sub-directory **/archive/** , you can use those attributes to make the recipe work again:

``` ruby
  :wkhtmltopdf => {
    :version => "0.12.0",
    :mirror_url => "http://downloads.sourceforge.net/project/wkhtmltopdf/archive/0.12.0/wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz",
    :archive => "wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz"
  }
```

**Comment by evanpurkhiser** [comment]
Yeah, I did end up doing something along those lines (sorry, I should have commented back here!). I'll leave this issue open though since the recipe needs updated also.

**Comment by klamontagne** [comment]
I'll post a PR shortly.
